import { SiteRenderer } from "@/components/siteflow/SiteRenderer";
import { appendNode, createElement, duplicateNode, elementLabels, findNode, patchNodeStyle, removeNode, reorderSibling, updateNode } from "@/components/siteflow/tree";
import { SiteFlowLogo } from "@/components/siteflow/AppShell";
import { useIsMobile } from "@/hooks/useMobile";
import { trpc } from "@/lib/trpc";
import type { DeviceMode, ElementNode, ElementType, StyleMap } from "../../../shared/siteflow";
import { AlignCenter, AlignLeft, AlignRight, Archive, ArrowDown, ArrowUp, BarChart3, Box, Check, ChevronDown, ChevronLeft, ChevronRight, CircleHelp, ClipboardCopy, Cloud, Code2, Copy, Database, Eye, FilePlus2, FileText, FolderOpen, FormInput, Globe2, Image, LayoutPanelLeft, Layers3, Link, Lock, Menu, Monitor, MoreHorizontal, MousePointer2, Palette, PanelLeftClose, Pencil, Plus, Redo2, Rocket, Search, Settings2, Smartphone, Sparkles, Tablet, Trash2, Undo2, Upload, Wand2, X } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import { Link as RouterLink, useLocation, useRoute } from "wouter";
import { toast } from "sonner";

type Panel = "add" | "components" | "pages" | "layers" | "theme" | "assets" | "cms" | "forms" | "seo" | "analytics" | "settings";

const toolGroups: Array<{ label: string; items: Array<{ panel: Panel; icon: typeof Plus; title: string }> }> = [
  { label: "Construire", items: [{ panel: "add", icon: Plus, title: "Ajouter" }, { panel: "components", icon: Box, title: "Composants" }, { panel: "layers", icon: Layers3, title: "Calques" }, { panel: "theme", icon: Palette, title: "Thème" }] },
  { label: "Contenu", items: [{ panel: "pages", icon: FileText, title: "Pages" }, { panel: "assets", icon: Image, title: "Assets" }, { panel: "cms", icon: Database, title: "CMS" }, { panel: "forms", icon: FormInput, title: "Formulaires" }] },
  { label: "Croître", items: [{ panel: "seo", icon: Search, title: "SEO" }, { panel: "analytics", icon: BarChart3, title: "Analytics" }, { panel: "settings", icon: Settings2, title: "Réglages" }] },
];

const elementGroups: Array<{ label: string; elements: ElementType[] }> = [
  { label: "Éléments", elements: ["heading", "paragraph", "button", "image", "divider", "spacer"] },
  { label: "Mise en page", elements: ["section", "container", "grid", "card"] },
  { label: "Navigation", elements: ["navbar", "footer"] },
  { label: "Formulaires", elements: ["form"] },
];

function deviceIcon(device: DeviceMode) { return device === "desktop" ? Monitor : device === "tablet" ? Tablet : Smartphone; }

export default function Editor() {
  const [, params] = useRoute("/editor/:id");
  const siteId = Number(params?.id);
  const [, setLocation] = useLocation();
  const isMobile = useIsMobile();
  const utils = trpc.useUtils();
  const siteQuery = trpc.siteflow.get.useQuery({ siteId }, { enabled: Number.isFinite(siteId) && siteId > 0 });
  const [activePanel, setActivePanel] = useState<Panel>("add");
  const [device, setDevice] = useState<DeviceMode>("desktop");
  const [currentPageId, setCurrentPageId] = useState<number | null>(null);
  const [tree, setTree] = useState<ElementNode[]>([]);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [history, setHistory] = useState<ElementNode[][]>([]);
  const [historyIndex, setHistoryIndex] = useState(-1);
  const [saveStatus, setSaveStatus] = useState<"saved" | "saving" | "unsaved">("saved");
  const [inspectorTab, setInspectorTab] = useState<"content" | "design" | "layout" | "responsive">("content");
  const [publishOpen, setPublishOpen] = useState(false);
  const [publishResult, setPublishResult] = useState(false);
  const [mobilePropertiesOpen, setMobilePropertiesOpen] = useState(false);
  const [zoom, setZoom] = useState(100);
  const pageHydrated = useRef<number | null>(null);
  const currentPage = useMemo(() => siteQuery.data?.pages.find((page) => page.id === currentPageId) ?? siteQuery.data?.pages[0], [currentPageId, siteQuery.data?.pages]);
  const selected = useMemo(() => selectedId ? findNode(tree, selectedId) : undefined, [selectedId, tree]);

  useEffect(() => {
    if (isMobile && device === "desktop") setDevice("mobile");
  }, [device, isMobile]);

  const savePage = trpc.siteflow.pages.update.useMutation({
    onSuccess: (data) => { utils.siteflow.get.setData({ siteId }, data); setSaveStatus("saved"); },
    onError: () => { setSaveStatus("unsaved"); toast.error("La sauvegarde n’a pas abouti."); },
  });
  const createPage = trpc.siteflow.pages.create.useMutation({ onSuccess: (result) => { utils.siteflow.get.setData({ siteId }, result.data); setCurrentPageId(result.pageId); toast.success("Nouvelle page créée."); } });
  const removePage = trpc.siteflow.pages.remove.useMutation({ onSuccess: (data) => { utils.siteflow.get.setData({ siteId }, data); setCurrentPageId(data.pages[0]?.id ?? null); toast.success("Page supprimée."); } });
  const updateSite = trpc.siteflow.update.useMutation({ onSuccess: (data) => { utils.siteflow.get.setData({ siteId }, data); toast.success("Réglages du site enregistrés."); } });
  const publishSite = trpc.siteflow.publish.useMutation({ onSuccess: (data) => { utils.siteflow.get.setData({ siteId }, data); setPublishResult(true); setPublishOpen(false); toast.success("Le site est publié."); } });

  useEffect(() => {
    if (!siteQuery.data?.pages.length) return;
    const target = siteQuery.data.pages.find((page) => page.id === currentPageId) ?? siteQuery.data.pages[0];
    if (pageHydrated.current === target.id) return;
    pageHydrated.current = target.id;
    setCurrentPageId(target.id);
    setTree(target.elementTree as ElementNode[]);
    setHistory([target.elementTree as ElementNode[]]);
    setHistoryIndex(0);
    setSelectedId((target.elementTree as ElementNode[]).find((node) => node.type === "section")?.id ?? target.elementTree[0]?.id ?? null);
    setInspectorTab("design");
    setSaveStatus("saved");
  }, [currentPageId, siteQuery.data?.pages]);

  useEffect(() => {
    if (!currentPage || historyIndex <= 0 || JSON.stringify(tree) === JSON.stringify(currentPage.elementTree)) return;
    setSaveStatus("saving");
    const timer = window.setTimeout(() => savePage.mutate({ pageId: currentPage.id, elementTree: tree }), 650);
    return () => window.clearTimeout(timer);
  }, [currentPage, historyIndex, savePage, tree]);

  function commit(next: ElementNode[]) {
    setTree(next);
    setHistory((previous) => {
      const slice = previous.slice(0, historyIndex + 1);
      return [...slice, next];
    });
    setHistoryIndex((previous) => previous + 1);
    setSaveStatus("unsaved");
  }

  function selectNode(node: ElementNode) { setSelectedId(node.id); setInspectorTab("content"); }
  function addElement(type: ElementType) {
    const element = createElement(type);
    const canContain = selected && ["section", "container", "grid", "card"].includes(selected.type);
    commit(appendNode(tree, element, canContain ? selected.id : undefined));
    setSelectedId(element.id);
    toast.success(`${elementLabels[type]} ajouté.`);
  }
  function addSectionPreset() {
    const section = createElement("section");
    section.name = "Section éditoriale";
    section.children = [createElement("heading"), createElement("paragraph"), createElement("button")];
    (section.children[0].props as { text: string }).text = "Une nouvelle section, déjà structurée.";
    commit([...tree, section]); setSelectedId(section.id); toast.success("Section ajoutée au canevas.");
  }
  function addComponent(kind: "hero" | "features" | "contact") {
    const section = createElement("section");
    if (kind === "hero") { section.name = "Hero · composant"; section.children = [createElement("heading"), createElement("paragraph"), createElement("button")]; (section.children[0].props as { text: string }).text = "Une introduction qui positionne votre idée."; }
    if (kind === "features") { section.name = "Grille de bénéfices · composant"; const grid = createElement("grid"); grid.children = [createElement("card"), createElement("card"), createElement("card")]; section.children = [createElement("heading"), grid]; (section.children[0].props as { text: string }).text = "Ce qui rend votre approche unique."; }
    if (kind === "contact") { section.name = "Contact · composant"; section.children = [createElement("heading"), createElement("paragraph"), createElement("form")]; (section.children[0].props as { text: string }).text = "Lancer la conversation."; }
    commit([...tree, section]); setSelectedId(section.id); toast.success("Composant ajouté au canevas.");
  }
  function updateSelectedNode(update: (node: ElementNode) => ElementNode) { if (!selected) return; commit(updateNode(tree, selected.id, update)); }
  function patchSelectedStyles(styles: StyleMap) { if (!selected) return; updateSelectedNode((node) => patchNodeStyle(node, styles, device)); }
  function changeSelectedProp(key: string, value: string) { updateSelectedNode((node) => ({ ...node, props: { ...node.props, [key]: value } })); }
  function undo() { if (historyIndex <= 0) return; const next = history[historyIndex - 1]; setTree(next); setHistoryIndex(historyIndex - 1); setSaveStatus("unsaved"); }
  function redo() { if (historyIndex >= history.length - 1) return; const next = history[historyIndex + 1]; setTree(next); setHistoryIndex(historyIndex + 1); setSaveStatus("unsaved"); }
  function saveNow() { if (!currentPage) return; setSaveStatus("saving"); savePage.mutate({ pageId: currentPage.id, elementTree: tree }); }
  function publishNow() { if (!currentPage) return; savePage.mutate({ pageId: currentPage.id, elementTree: tree }, { onSuccess: () => publishSite.mutate({ siteId }) }); }

  if (siteQuery.isLoading) return <div className="grid min-h-screen place-items-center bg-[#F8F8FC]"><div className="siteflow-loader" /></div>;
  if (!siteQuery.data || !currentPage) return <div className="grid min-h-screen place-items-center bg-[#F8F8FC]"><div className="text-center"><h1 className="font-display text-4xl">Projet introuvable.</h1><button className="siteflow-primary-btn mt-4" onClick={() => setLocation("/")}>Retour aux sites</button></div></div>;
  const site = siteQuery.data.site;
  const DeviceIcon = deviceIcon(device);
  const canvasWidth = device === "desktop" ? "min(100%, 990px)" : device === "tablet" ? "760px" : "390px";

  return <div className="siteflow-editor min-h-screen bg-[#F6F6FA] text-[#11172B]">
    <header className="siteflow-editor-header">
      <div className="flex min-w-0 items-center gap-5"><RouterLink href="/" className="hidden xl:block"><SiteFlowLogo /></RouterLink><div className="hidden h-7 border-l border-[#DDDDE8] xl:block" /><div className="min-w-0"><div className="flex items-center gap-2"><button onClick={() => setActivePanel("settings")} className="truncate text-sm font-extrabold hover:text-[#2925D8]">{site.name}</button><ChevronDown className="h-3.5 w-3.5 text-[#777A8E]" /></div><span className={`mt-0.5 block text-[11px] font-semibold ${saveStatus === "saved" ? "text-[#488261]" : saveStatus === "saving" ? "text-[#887132]" : "text-[#AB5560]"}`}>{saveStatus === "saved" ? "Enregistré à l’instant" : saveStatus === "saving" ? "Sauvegarde…" : "Modifications à enregistrer"}</span></div></div>
      <div className="hidden items-center gap-1 lg:flex"><button className="siteflow-icon-btn" onClick={undo} disabled={historyIndex <= 0} aria-label="Annuler"><Undo2 className="h-4 w-4" /></button><button className="siteflow-icon-btn" onClick={redo} disabled={historyIndex >= history.length - 1} aria-label="Rétablir"><Redo2 className="h-4 w-4" /></button><span className="mx-2 h-5 border-l border-[#E0E0EB]" />{(["desktop", "tablet", "mobile"] as DeviceMode[]).map((item) => { const Icon = deviceIcon(item); return <button key={item} onClick={() => setDevice(item)} className={`siteflow-icon-btn ${device === item ? "siteflow-icon-btn-active" : ""}`} aria-label={`Passer en vue ${item}`}><Icon className="h-4 w-4" /></button> })}<span className="mx-2 h-5 border-l border-[#E0E0EB]" /><button onClick={() => setZoom((value) => value === 100 ? 85 : value === 85 ? 75 : 100)} className="flex items-center gap-1 rounded-lg px-2 py-2 text-xs font-bold hover:bg-[#F0F0F5]">{zoom}%<ChevronDown className="h-3.5 w-3.5" /></button></div>
      <div className="flex items-center gap-2"><button onClick={saveNow} className="hidden rounded-lg px-3 py-2 text-xs font-bold text-[#555970] hover:bg-[#EFEFF5] sm:block">Sauvegarder</button><button onClick={() => setLocation(`/preview/${siteId}`)} className="siteflow-secondary-btn !px-3 !py-2 text-xs"><Eye className="h-3.5 w-3.5" />Aperçu</button><button onClick={() => setPublishOpen(true)} className="siteflow-primary-btn !px-3 !py-2 text-xs"><Rocket className="h-3.5 w-3.5" />Publier</button></div>
    </header>
    <div className="flex min-h-[calc(100vh-69px)]">
      <aside className="siteflow-editor-rail"><div className="flex flex-1 flex-col gap-3 py-4">{toolGroups.map((group) => <div key={group.label} className="space-y-1">{group.items.map((item) => <button key={item.panel} onClick={() => setActivePanel(item.panel)} className={`siteflow-rail-btn ${activePanel === item.panel ? "siteflow-rail-btn-active" : ""}`} title={item.title}><item.icon className="h-[19px] w-[19px]" /></button>)}</div>)}</div><button className="siteflow-rail-btn mb-4" title="Aide"><CircleHelp className="h-5 w-5" /></button></aside>
      <aside className="siteflow-editor-panel">{activePanel === "add" && <AddPanel onAdd={addElement} onAddSection={addSectionPreset} />}{activePanel === "components" && <ComponentsPanel onAdd={addComponent} />}{activePanel === "pages" && <PagesPanel pages={siteQuery.data.pages} currentPageId={currentPage.id} onSelect={(pageId) => { pageHydrated.current = null; setCurrentPageId(pageId); }} onAdd={() => { const name = window.prompt("Nom de la nouvelle page", "Nouvelle page"); if (name) createPage.mutate({ siteId, name }); }} onDelete={(pageId) => window.confirm("Supprimer cette page ?") && removePage.mutate({ pageId })} onUpdateSettings={(settings) => savePage.mutate({ pageId: currentPage.id, settings })} currentPage={currentPage} />}{activePanel === "layers" && <LayersPanel nodes={tree} selectedId={selectedId} onSelect={setSelectedId} onToggle={(id, key) => { const node = findNode(tree, id); if (node) commit(updateNode(tree, id, (item) => ({ ...item, [key]: !item[key] }))); }} onDelete={(id) => { commit(removeNode(tree, id)); setSelectedId(null); }} onDuplicate={(id) => commit(duplicateNode(tree, id))} onMove={(id, direction) => commit(reorderSibling(tree, id, direction))} />}{activePanel === "theme" && <ThemePanel theme={site.theme} onUpdate={(theme) => updateSite.mutate({ siteId, theme })} />}{activePanel === "assets" && <AssetsPanel siteId={siteId} />}{activePanel === "cms" && <CmsPanel siteId={siteId} />}{activePanel === "forms" && <FormsPanel siteId={siteId} />}{activePanel === "seo" && <SeoPanel page={currentPage} onSave={(settings) => savePage.mutate({ pageId: currentPage.id, settings })} />}{activePanel === "analytics" && <AnalyticsPanel />}{activePanel === "settings" && <SettingsPanel siteName={site.name} siteId={siteId} onRename={(name) => updateSite.mutate({ siteId, name })} />}</aside>
      <main className="siteflow-canvas-wrap"><div className="siteflow-canvas-toolbar lg:hidden"><button onClick={() => setActivePanel("add")}><Plus className="h-4 w-4" />Ajouter</button><button onClick={() => setActivePanel("pages")}><FileText className="h-4 w-4" />Pages</button><button onClick={() => setActivePanel("layers")}><Layers3 className="h-4 w-4" />Calques</button><button onClick={() => setActivePanel("theme")}><Palette className="h-4 w-4" />Design</button><button onClick={() => setActivePanel("assets")}><Image className="h-4 w-4" />Assets</button><button onClick={() => setActivePanel("settings")}><MoreHorizontal className="h-4 w-4" />Plus</button></div><div className="siteflow-canvas-stage"><div className="siteflow-canvas-zoom" style={{ width: canvasWidth, transform: `scale(${zoom / 100})`, transformOrigin: "top center" }}><div className="siteflow-document" onClick={() => setSelectedId(null)}><SiteRenderer nodes={tree} device={device} editable selectedId={selectedId} onSelect={selectNode} onResize={(node, width) => updateSelectedNode((item) => item.id === node.id ? patchNodeStyle(item, { width: `${width}px` }, device) : item)} onMove={(node, delta) => updateSelectedNode((item) => item.id === node.id ? patchNodeStyle(item, { marginLeft: `${(parseInt(String(item.styles.marginLeft ?? 0), 10) || 0) + delta.x}px`, marginTop: `${(parseInt(String(item.styles.marginTop ?? 0), 10) || 0) + delta.y}px` }, device) : item)} /></div></div></div></main>
      <aside className="siteflow-inspector"><Inspector node={selected} device={device} tab={inspectorTab} onTab={setInspectorTab} onChangeProp={changeSelectedProp} onStyles={patchSelectedStyles} onRename={(name) => updateSelectedNode((item) => ({ ...item, name }))} onDelete={() => { if (selected) { commit(removeNode(tree, selected.id)); setSelectedId(null); } }} onDuplicate={() => selected && commit(duplicateNode(tree, selected.id))} /></aside>
    </div>
    {publishOpen ? <PublishDialog site={site} pages={siteQuery.data.pages} onClose={() => setPublishOpen(false)} onPublish={publishNow} loading={publishSite.isPending || savePage.isPending} /> : null}
    {publishResult ? <PublishResult slug={siteQuery.data.site.slug} onClose={() => setPublishResult(false)} /> : null}
    {selected ? <div className="siteflow-mobile-properties lg:hidden"><div><span className="block text-[10px] font-extrabold uppercase tracking-[.12em] text-[#6D70D8]">Élément sélectionné</span><strong className="mt-0.5 block text-xs">{selected.name}</strong></div><button onClick={() => { setInspectorTab("content"); setMobilePropertiesOpen(true); }} className="siteflow-secondary-btn !px-3 !py-2 text-[11px]" aria-label="Ouvrir les propriétés">Propriétés</button></div> : null}
    {selected && mobilePropertiesOpen ? <div className="siteflow-mobile-sheet-backdrop lg:hidden" onClick={() => setMobilePropertiesOpen(false)}><section className="siteflow-mobile-sheet" onClick={(event) => event.stopPropagation()}><div className="mb-4 flex items-center justify-between"><div><p className="text-[10px] font-extrabold uppercase tracking-[.14em] text-[#7074D7]">Propriétés</p><h3 className="mt-1 text-sm font-extrabold">{selected.name}</h3></div><button onClick={() => setMobilePropertiesOpen(false)} className="siteflow-icon-btn"><X className="h-4 w-4" /></button></div><div className="flex border-b border-[#E6E6ED]">{([{ id: "content", label: "Contenu" }, { id: "design", label: "Design" }, { id: "layout", label: "Layout" }, { id: "responsive", label: "Resp." }] as const).map((item) => <button key={item.id} onClick={() => setInspectorTab(item.id)} className={`flex-1 border-b-2 px-1 py-2 text-[10px] font-extrabold ${inspectorTab === item.id ? "border-[#2925D8] text-[#2925D8]" : "border-transparent text-[#878A9A]"}`}>{item.label}</button>)}</div><div className="max-h-[48vh] overflow-y-auto pt-4">{inspectorTab === "content" ? <ContentFields node={selected} onChange={changeSelectedProp} /> : null}{inspectorTab === "design" ? <DesignFields node={selected} onStyles={patchSelectedStyles} /> : null}{inspectorTab === "layout" ? <LayoutFields node={selected} onStyles={patchSelectedStyles} /> : null}{inspectorTab === "responsive" ? <ResponsiveFields node={selected} device={device} onStyles={patchSelectedStyles} /> : null}</div></section></div> : null}
  </div>;
}

function AddPanel({ onAdd, onAddSection }: { onAdd: (type: ElementType) => void; onAddSection: () => void }) { const [query, setQuery] = useState(""); const normalized = query.trim().toLowerCase(); return <PanelShell title="Ajouter des éléments" subtitle="Composez votre page à partir d’éléments et de structures."><label className="siteflow-search mb-6"><Search className="h-4 w-4" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Rechercher des composants…" /></label><button onClick={onAddSection} className="mb-6 flex w-full items-center gap-3 rounded-lg border border-[#CFCFF5] bg-[#F7F7FF] p-3 text-left"><span className="grid h-9 w-9 place-items-center rounded-md bg-[#2925D8] text-white"><Wand2 className="h-4 w-4" /></span><span><strong className="block text-xs">Ajouter une section</strong><small className="block pt-0.5 text-[11px] text-[#676BD0]">Un bloc déjà structuré.</small></span></button>{elementGroups.map((group) => { const elements = group.elements.filter((element) => !normalized || `${elementLabels[element]} ${element}`.toLowerCase().includes(normalized)); return elements.length ? <div key={group.label} className="mb-6"><p className="mb-2 text-[10px] font-extrabold uppercase tracking-[.14em] text-[#687082]">{group.label}</p><div className="grid grid-cols-2 gap-2">{elements.map((element) => <button key={element} onClick={() => onAdd(element)} className="siteflow-element-tile"><span className="mx-auto grid h-8 w-8 place-items-center rounded-md bg-[#F5F6FA] text-[#41485A]">{element === "heading" ? "T" : element === "paragraph" ? "≡" : element === "button" ? "↗" : element === "image" ? "◉" : element === "grid" ? "▦" : element === "section" ? "▤" : element === "form" ? "⌁" : "—"}</span>{elementLabels[element]}</button>)}</div></div> : null; })}</PanelShell> }
function ComponentsPanel({ onAdd }: { onAdd: (kind: "hero" | "features" | "contact") => void }) { const cards = [{ kind: "hero" as const, title: "Hero éditorial", copy: "Titre, texte et action primaire.", glyph: "Aa" }, { kind: "features" as const, title: "Bénéfices en grille", copy: "Titre et trois cartes de contenu.", glyph: "▦" }, { kind: "contact" as const, title: "Bloc contact", copy: "Introduction et formulaire prêt à l’emploi.", glyph: "⌁" }]; return <PanelShell title="Composants" subtitle="Des compositions réutilisables, pas seulement des éléments isolés."><div className="space-y-3">{cards.map((card) => <button key={card.kind} onClick={() => onAdd(card.kind)} className="group w-full rounded-xl border border-[#E3E3EC] bg-white p-3 text-left transition-all hover:-translate-y-0.5 hover:border-[#BDBEE5] hover:shadow-[0_8px_18px_rgba(41,37,216,.08)]"><span className="grid h-12 w-full place-items-center rounded-lg bg-[#F3F3FA] font-display text-2xl text-[#4B4FB7]">{card.glyph}</span><strong className="mt-3 block text-xs">{card.title}</strong><small className="mt-1 block text-[11px] leading-5 text-[#777A8C]">{card.copy}</small><span className="mt-3 inline-flex items-center gap-1 text-[11px] font-extrabold text-[#2925D8]">Ajouter au canevas <Plus className="h-3 w-3" /></span></button>)}</div></PanelShell> }
function PagesPanel({ pages, currentPageId, onSelect, onAdd, onDelete, onUpdateSettings, currentPage }: { pages: Array<{ id: number; name: string; slug: string; isHomepage: boolean; settings: Record<string, unknown> }>; currentPageId: number; onSelect: (id: number) => void; onAdd: () => void; onDelete: (id: number) => void; onUpdateSettings: (settings: Record<string, unknown>) => void; currentPage: { id: number; name: string; slug: string; settings: Record<string, unknown> } }) { return <PanelShell title="Pages" subtitle="Les routes et les paramètres du site."><button onClick={onAdd} className="siteflow-primary-btn mb-5 w-full justify-center !py-2.5 text-xs"><Plus className="h-3.5 w-3.5" />Ajouter une page</button><div className="space-y-1">{pages.map((page) => <div key={page.id} className={`group flex items-center gap-2 rounded-xl border px-3 py-3 ${page.id === currentPageId ? "border-[#CFCFF2] bg-[#F5F5FF]" : "border-transparent hover:bg-[#F5F5F9]"}`}><button onClick={() => onSelect(page.id)} className="flex min-w-0 flex-1 items-center gap-2 text-left"><FileText className="h-4 w-4 text-[#6569D4]" /><span className="min-w-0"><strong className="block truncate text-xs">{page.name}</strong><small className="block truncate text-[10px] text-[#898C9C]">/{page.slug}{page.isHomepage ? " · Accueil" : ""}</small></span></button>{pages.length > 1 ? <button onClick={() => onDelete(page.id)} className="opacity-0 transition-opacity group-hover:opacity-100" aria-label="Supprimer la page"><Trash2 className="h-3.5 w-3.5 text-[#A6555F]" /></button> : null}</div>)}</div><div className="mt-7 border-t border-[#E8E8F0] pt-5"><p className="mb-4 text-[10px] font-extrabold uppercase tracking-[.14em] text-[#8A8D9C]">Réglages de la page</p><label className="siteflow-field"><span>URL</span><input value={currentPage.slug} onChange={(event) => onUpdateSettings({ ...currentPage.settings, slug: event.target.value })} placeholder="page" /></label><label className="siteflow-field"><span>Titre SEO</span><input value={String(currentPage.settings.title ?? "")} onChange={(event) => onUpdateSettings({ ...currentPage.settings, title: event.target.value })} placeholder="Titre de page" /></label></div></PanelShell> }
function LayersPanel({ nodes, selectedId, onSelect, onToggle, onDelete, onDuplicate, onMove }: { nodes: ElementNode[]; selectedId: string | null; onSelect: (id: string) => void; onToggle: (id: string, key: "visible" | "locked") => void; onDelete: (id: string) => void; onDuplicate: (id: string) => void; onMove: (id: string, direction: "up" | "down") => void }) { const render = (items: ElementNode[], depth = 0) => items.map((node) => <div key={node.id}><div className={`group flex items-center gap-2 rounded-lg py-2 pl-${depth ? "" : ""}`} style={{ paddingLeft: 10 + depth * 14 }}><button onClick={() => onSelect(node.id)} className={`min-w-0 flex-1 truncate text-left text-xs ${selectedId === node.id ? "font-bold text-[#2925D8]" : "text-[#4D5166]"}`}>{node.name}</button><button onClick={() => onMove(node.id, "up")} className="opacity-0 group-hover:opacity-100" aria-label="Monter"><ArrowUp className="h-3 w-3" /></button><button onClick={() => onMove(node.id, "down")} className="opacity-0 group-hover:opacity-100" aria-label="Descendre"><ArrowDown className="h-3 w-3" /></button><button onClick={() => onToggle(node.id, "visible")} className="opacity-0 group-hover:opacity-100" aria-label="Afficher ou masquer"><Eye className={`h-3.5 w-3.5 ${node.visible ? "" : "text-[#AAA]"}`} /></button><button onClick={() => onDuplicate(node.id)} className="opacity-0 group-hover:opacity-100" aria-label="Dupliquer"><Copy className="h-3 w-3" /></button><button onClick={() => onDelete(node.id)} className="opacity-0 group-hover:opacity-100" aria-label="Supprimer"><Trash2 className="h-3.5 w-3.5 text-[#AA525F]" /></button></div>{node.children.length ? render(node.children, depth + 1) : null}</div>); return <PanelShell title="Calques" subtitle="Réorganisez la structure de votre page."><div className="rounded-xl border border-[#E6E6EE] bg-white p-1">{render(nodes)}</div></PanelShell> }
function ThemePanel({ theme, onUpdate }: { theme: { background: string; foreground: string; accent: string; fontDisplay: string; fontBody: string }; onUpdate: (theme: { background: string; foreground: string; accent: string; fontDisplay: string; fontBody: string }) => void }) { const update = (key: "background" | "foreground" | "accent", value: string) => onUpdate({ ...theme, [key]: value }); return <PanelShell title="Thème" subtitle="Une base cohérente pour chaque page."><div className="space-y-3"><ThemeToken label="Fond" value={theme.background} onChange={(value) => update("background", value)} /><ThemeToken label="Texte" value={theme.foreground} onChange={(value) => update("foreground", value)} /><ThemeToken label="Accent" value={theme.accent} onChange={(value) => update("accent", value)} /></div><div className="mt-7 border-t border-[#E8E8F0] pt-5"><p className="mb-3 text-[10px] font-extrabold uppercase tracking-[.14em] text-[#8A8D9C]">Typographie</p><div className="rounded-xl border border-[#E7E7EF] bg-white p-4"><p className="font-display text-2xl">{theme.fontDisplay}</p><p className="mt-2 text-xs text-[#717487]">Titres et accents éditoriaux</p></div><div className="mt-3 rounded-xl border border-[#E7E7EF] bg-white p-4"><p className="text-sm font-semibold">{theme.fontBody}</p><p className="mt-2 text-xs text-[#717487]">Lecture et interface</p></div></div></PanelShell> }
function ThemeToken({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="flex items-center justify-between rounded-xl border border-[#E6E6EE] bg-white p-3"><span className="flex items-center gap-2 text-xs font-bold"><i className="h-5 w-5 rounded-md border border-black/10" style={{ background: value }} />{label}</span><input className="h-7 w-8 rounded border-0 bg-transparent p-0" type="color" value={value} onChange={(event) => onChange(event.target.value)} aria-label={`Couleur ${label}`} /></label> }
function AssetsPanel({ siteId }: { siteId: number }) { const utils = trpc.useUtils(); const query = trpc.siteflow.assets.list.useQuery(); const upload = trpc.siteflow.assets.upload.useMutation({ onSuccess: () => { utils.siteflow.assets.list.invalidate(); toast.success("Asset importé dans votre espace."); }, onError: (error) => toast.error(error.message) }); const fallback = ["/manus-storage/template-nexus-saas_c284fccd.png", "/manus-storage/template-canvas-portfolio_56be5412.png", "/manus-storage/template-atelier-restaurant_a7a3c5f0.png", "/manus-storage/template-arc-real-estate_e312de0e.png"]; const assets = query.data?.length ? query.data.map((asset) => asset.url) : fallback; function handleFile(file?: File) { if (!file) return; if (file.size > 5 * 1024 * 1024) { toast.error("Choisissez un fichier de 5 Mo maximum."); return; } const reader = new FileReader(); reader.onload = () => { const kind = file.type.startsWith("image/") ? "image" : file.type.startsWith("video/") ? "video" : file.type.includes("svg") ? "svg" : file.type.includes("font") ? "font" : "document"; upload.mutate({ name: file.name, kind, contentType: file.type || "application/octet-stream", dataUrl: String(reader.result) }); }; reader.readAsDataURL(file); } return <PanelShell title="Assets" subtitle="Vos images, fichiers et composants de marque."><label className="siteflow-secondary-btn mb-5 flex w-full justify-center !py-2.5 text-xs"><Upload className="h-3.5 w-3.5" />{upload.isPending ? "Import…" : "Importer un fichier"}<input type="file" className="sr-only" onChange={(event) => handleFile(event.target.files?.[0])} disabled={upload.isPending} /></label><div className="grid grid-cols-2 gap-2">{assets.map((asset) => <img key={asset} src={asset} alt="" className="h-20 w-full rounded-lg border border-[#E3E3EB] object-cover" />)}</div><p className="mt-5 text-xs leading-5 text-[#7A7D8F]">{query.data?.length ?? 0} fichier(s) enregistré(s) dans votre espace. Formats image, vidéo, SVG, police et document, 5 Mo maximum.</p></PanelShell> }
function CmsPanel({ siteId }: { siteId: number }) { const utils = trpc.useUtils(); const query = trpc.siteflow.cms.list.useQuery({ siteId }); const mutation = trpc.siteflow.cms.create.useMutation({ onSuccess: () => utils.siteflow.cms.list.invalidate({ siteId }) }); return <PanelShell title="CMS" subtitle="Collections dynamiques et contenu structuré."><button onClick={() => { const name = window.prompt("Nom de la collection", "Articles"); if (name) mutation.mutate({ siteId, name }); }} className="siteflow-primary-btn mb-5 w-full justify-center !py-2.5 text-xs"><Plus className="h-3.5 w-3.5" />Nouvelle collection</button><div className="space-y-2">{(query.data ?? []).map((collection) => <div key={collection.id} className="rounded-xl border border-[#E5E5EE] bg-white p-3"><strong className="block text-xs">{collection.name}</strong><small className="mt-1 block text-[11px] text-[#777A8B]">/{collection.slug} · {collection.schema.length} champs</small></div>)}{!query.data?.length ? <EmptyPanel icon={Database} text="Créez votre première collection, par exemple Articles ou Projets." /> : null}</div></PanelShell> }
function FormsPanel({ siteId }: { siteId: number }) { const utils = trpc.useUtils(); const query = trpc.siteflow.forms.list.useQuery({ siteId }); const mutation = trpc.siteflow.forms.create.useMutation({ onSuccess: () => utils.siteflow.forms.list.invalidate({ siteId }) }); return <PanelShell title="Formulaires" subtitle="Captez les messages depuis vos pages."><button onClick={() => { const name = window.prompt("Nom du formulaire", "Contact"); if (name) mutation.mutate({ siteId, name }); }} className="siteflow-primary-btn mb-5 w-full justify-center !py-2.5 text-xs"><Plus className="h-3.5 w-3.5" />Créer un formulaire</button><div className="space-y-2">{(query.data ?? []).map((form) => <div key={form.id} className="rounded-xl border border-[#E5E5EE] bg-white p-3"><strong className="block text-xs">{form.name}</strong><small className="mt-1 block text-[11px] text-[#777A8B]">{form.fields.length} champs · Aucune soumission</small></div>)}{!query.data?.length ? <EmptyPanel icon={FormInput} text="Les formulaires créés ici pourront être ajoutés à une section depuis l’onglet Ajouter." /> : null}</div></PanelShell> }
function SeoPanel({ page, onSave }: { page: { slug: string; settings: Record<string, unknown> }; onSave: (settings: Record<string, unknown>) => void }) { return <PanelShell title="SEO" subtitle="Rendez votre page nette pour la recherche."><div className="rounded-xl border border-[#DADBF0] bg-[#F6F6FF] p-4"><p className="text-[10px] font-extrabold uppercase tracking-[.14em] text-[#7276D7]">Score préparatoire</p><p className="mt-2 font-display text-5xl text-[#2925D8]">82<span className="text-lg">/100</span></p><p className="mt-2 text-[11px] leading-5 text-[#6C70A0]">Complétez le titre et la description pour améliorer ce score.</p></div><div className="mt-5 space-y-3"><label className="siteflow-field"><span>Titre SEO</span><input value={String(page.settings.title ?? "")} onChange={(event) => onSave({ ...page.settings, title: event.target.value })} /></label><label className="siteflow-field"><span>Description</span><textarea value={String(page.settings.description ?? "")} onChange={(event) => onSave({ ...page.settings, description: event.target.value })} /></label><label className="siteflow-field"><span>URL</span><input value={`/${page.slug}`} readOnly /></label></div></PanelShell> }
function AnalyticsPanel() { return <PanelShell title="Analytics" subtitle="Lecture d’audience · données de démonstration."><div className="grid grid-cols-2 gap-2"><Metric label="Visiteurs" value="1 248" /><Metric label="Vues" value="3 906" /><Metric label="Sessions" value="1 633" /><Metric label="Conv." value="3,8 %" /></div><div className="mt-5 rounded-xl border border-[#E4E4ED] bg-white p-4"><p className="text-xs font-bold">Trafic sur 30 jours</p><div className="mt-5 flex h-24 items-end gap-1.5">{[36, 52, 44, 68, 58, 82, 67, 92, 75, 88, 100, 83].map((height, index) => <span key={index} className="flex-1 rounded-t bg-[#2925D8]/80" style={{ height: `${height}%` }} />)}</div></div><p className="mt-4 text-[11px] leading-5 text-[#85889A]">Ces métriques sont des données de démonstration tant qu’un suivi de production n’est pas connecté.</p></PanelShell> }
function SettingsPanel({ siteName, siteId, onRename }: { siteName: string; siteId: number; onRename: (name: string) => void }) { const utils = trpc.useUtils(); const versions = trpc.siteflow.versions.useQuery({ siteId }); const restore = trpc.siteflow.restoreVersion.useMutation({ onSuccess: (data) => { utils.siteflow.get.setData({ siteId }, data); utils.siteflow.versions.invalidate({ siteId }); toast.success("Version restaurée."); } }); return <PanelShell title="Réglages" subtitle="Contrôlez l’identité et les options du projet."><label className="siteflow-field"><span>Nom du site</span><input defaultValue={siteName} onBlur={(event) => event.target.value.trim() && event.target.value !== siteName && onRename(event.target.value)} /></label><div className="mt-6 space-y-2"><SettingsRow icon={Globe2} label="Domaine" value="siteflow.local" /><SettingsRow icon={ClipboardCopy} label="Identifiant du site" value={`#${siteId}`} /></div><div className="mt-7 border-t border-[#E7E7EF] pt-5"><p className="mb-3 text-[10px] font-extrabold uppercase tracking-[.14em] text-[#8A8D9C]">Historique des versions</p>{versions.data?.length ? <div className="space-y-2">{versions.data.map((version) => <div key={version.id} className="rounded-xl border border-[#E5E5EE] bg-white p-3"><strong className="block text-xs">{version.description}</strong><small className="mt-1 block text-[11px] text-[#818496]">{new Date(version.createdAt).toLocaleString("fr-FR")}</small><button onClick={() => window.confirm("Restaurer cette version ?") && restore.mutate({ versionId: version.id })} className="mt-2 text-[11px] font-extrabold text-[#2925D8]">Restaurer</button></div>)}</div> : <EmptyPanel icon={Archive} text="Une version est enregistrée à chaque publication." />}</div></PanelShell> }
function Inspector({ node, device, tab, onTab, onChangeProp, onStyles, onRename, onDelete, onDuplicate }: { node?: ElementNode; device: DeviceMode; tab: "content" | "design" | "layout" | "responsive"; onTab: (tab: "content" | "design" | "layout" | "responsive") => void; onChangeProp: (key: string, value: string) => void; onStyles: (styles: StyleMap) => void; onRename: (name: string) => void; onDelete: () => void; onDuplicate: () => void }) { if (!node) return <aside className="siteflow-inspector-empty"><MousePointer2 className="h-6 w-6 text-[#777BD7]" /><h3 className="mt-4 font-display text-2xl">Sélectionnez un élément.</h3><p className="mt-2 text-center text-xs leading-5 text-[#777A8D]">Cliquez dans le canevas pour ouvrir ses propriétés de contenu, design et mise en page.</p></aside>; return <div className="h-full overflow-y-auto"><div className="border-b border-[#E6E6ED] p-5"><div className="flex items-center justify-between"><span className="rounded-md bg-[#F0F0FF] px-2 py-1 text-[10px] font-extrabold uppercase tracking-[.1em] text-[#2925D8]">{elementLabels[node.type]}</span><div className="flex gap-1"><button onClick={onDuplicate} className="siteflow-icon-btn !h-7 !w-7" aria-label="Dupliquer"><Copy className="h-3.5 w-3.5" /></button><button onClick={onDelete} className="siteflow-icon-btn !h-7 !w-7 text-[#AA5260]" aria-label="Supprimer"><Trash2 className="h-3.5 w-3.5" /></button></div></div><input value={node.name} onChange={(event) => onRename(event.target.value)} className="mt-3 w-full bg-transparent text-sm font-bold outline-none" /></div><div className="flex border-b border-[#E6E6ED] px-3">{([{ id: "content", label: "Contenu" }, { id: "design", label: "Design" }, { id: "layout", label: "Layout" }, { id: "responsive", label: "Resp." }] as const).map((item) => <button key={item.id} onClick={() => onTab(item.id)} className={`flex-1 border-b-2 px-1 py-3 text-[10px] font-extrabold ${tab === item.id ? "border-[#2925D8] text-[#2925D8]" : "border-transparent text-[#878A9A]"}`}>{item.label}</button>)}</div><div className="p-5">{tab === "content" ? <ContentFields node={node} onChange={onChangeProp} /> : null}{tab === "design" ? <DesignFields node={node} onStyles={onStyles} /> : null}{tab === "layout" ? <LayoutFields node={node} onStyles={onStyles} /> : null}{tab === "responsive" ? <ResponsiveFields node={node} device={device} onStyles={onStyles} /> : null}</div></div> }
function ContentFields({ node, onChange }: { node: ElementNode; onChange: (key: string, value: string) => void }) { if (["heading", "paragraph"].includes(node.type)) return <label className="siteflow-field"><span>Texte</span><textarea value={String(node.props.text ?? "")} onChange={(event) => onChange("text", event.target.value)} /></label>; if (node.type === "button") return <div className="space-y-3"><label className="siteflow-field"><span>Libellé</span><input value={String(node.props.label ?? "")} onChange={(event) => onChange("label", event.target.value)} /></label><label className="siteflow-field"><span>Lien</span><input value={String(node.props.href ?? "")} onChange={(event) => onChange("href", event.target.value)} /></label></div>; if (node.type === "image") return <div className="space-y-3"><label className="siteflow-field"><span>URL de l’image</span><input value={String(node.props.src ?? "")} onChange={(event) => onChange("src", event.target.value)} /></label><label className="siteflow-field"><span>Texte alternatif</span><input value={String(node.props.alt ?? "")} onChange={(event) => onChange("alt", event.target.value)} /></label></div>; return <div className="rounded-xl border border-[#E5E5EE] bg-[#FAFAFC] p-4 text-xs leading-5 text-[#777A8C]">Cet élément est structurel. Utilisez Design et Layout pour ajuster son rendu.</div> }
function DesignFields({ node, onStyles }: { node: ElementNode; onStyles: (styles: StyleMap) => void }) { return <div className="space-y-4"><InspectorGroup title="Typographie"><label className="siteflow-field"><span>Famille</span><select value={String(node.styles.fontFamily ?? "Plus Jakarta Sans")} onChange={(event) => onStyles({ fontFamily: event.target.value })}><option>Plus Jakarta Sans</option><option>DM Serif Display</option><option>Inter</option></select></label><div className="grid grid-cols-2 gap-3"><label className="siteflow-field"><span>Poids</span><select value={String(node.styles.fontWeight ?? "700")} onChange={(event) => onStyles({ fontWeight: event.target.value })}><option value="400">Regular (400)</option><option value="600">Semibold (600)</option><option value="700">Bold (700)</option></select></label><label className="siteflow-field"><span>Taille</span><input value={String(node.styles.fontSize ?? "")} onChange={(event) => onStyles({ fontSize: event.target.value })} placeholder="48 px" /></label></div><div className="grid grid-cols-3 gap-2"><button onClick={() => onStyles({ textAlign: "left" })} className="siteflow-toggle"><AlignLeft className="h-4 w-4" /></button><button onClick={() => onStyles({ textAlign: "center" })} className="siteflow-toggle"><AlignCenter className="h-4 w-4" /></button><button onClick={() => onStyles({ textAlign: "right" })} className="siteflow-toggle"><AlignRight className="h-4 w-4" /></button></div></InspectorGroup><InspectorGroup title="Couleurs"><label className="siteflow-field"><span>Arrière-plan</span><span className="flex gap-2"><input type="color" value={String(node.styles.background ?? "#F8F8FC")} onChange={(event) => onStyles({ background: event.target.value })} /><input value={String(node.styles.background ?? "#F8F8FC")} onChange={(event) => onStyles({ background: event.target.value })} /></span></label><label className="siteflow-field"><span>Texte principal</span><span className="flex gap-2"><input type="color" value={String(node.styles.color ?? "#11172B")} onChange={(event) => onStyles({ color: event.target.value })} /><input value={String(node.styles.color ?? "#11172B")} onChange={(event) => onStyles({ color: event.target.value })} /></span></label></InspectorGroup><InspectorGroup title="Bordures et ombres" muted><label className="siteflow-field"><span>Rayon</span><input value={String(node.styles.borderRadius ?? "")} onChange={(event) => onStyles({ borderRadius: event.target.value })} placeholder="16 px" /></label></InspectorGroup></div> }
function InspectorGroup({ title, children, muted = false }: { title: string; children: React.ReactNode; muted?: boolean }) { return <section className={`siteflow-inspector-group ${muted ? "siteflow-inspector-group-muted" : ""}`}><header><strong>{title}</strong><ChevronDown className="h-4 w-4" /></header>{muted ? <div className="pt-3">{children}</div> : <div className="space-y-3 pt-4">{children}</div>}</section> }
function LayoutFields({ node, onStyles }: { node: ElementNode; onStyles: (styles: StyleMap) => void }) { return <div className="space-y-4"><label className="siteflow-field"><span>Largeur</span><input value={String(node.styles.width ?? "")} onChange={(event) => onStyles({ width: event.target.value })} placeholder="ex. 600px ou 100%" /></label><label className="siteflow-field"><span>Hauteur</span><input value={String(node.styles.height ?? "")} onChange={(event) => onStyles({ height: event.target.value })} placeholder="ex. auto" /></label><label className="siteflow-field"><span>Padding</span><input value={String(node.styles.padding ?? "")} onChange={(event) => onStyles({ padding: event.target.value })} placeholder="ex. 48px 7vw" /></label><label className="siteflow-field"><span>Marge</span><input value={String(node.styles.margin ?? "")} onChange={(event) => onStyles({ margin: event.target.value })} placeholder="ex. 0 auto" /></label></div> }
function ResponsiveFields({ node, device, onStyles }: { node: ElementNode; device: DeviceMode; onStyles: (styles: StyleMap) => void }) { const active = device === "desktop" ? "desktop" : device; const styles = device === "desktop" ? node.styles : node.responsive[device] ?? {}; return <div><div className="rounded-xl border border-[#D9DAF0] bg-[#F4F4FF] p-3 text-[11px] leading-5 text-[#6165B7]">Vous modifiez <strong>{active}</strong>. Les ajustements ne remplacent pas les valeurs Desktop.</div><div className="mt-4 space-y-3"><label className="siteflow-field"><span>Largeur</span><input value={String(styles.width ?? "")} onChange={(event) => onStyles({ width: event.target.value })} placeholder="ex. 100%" /></label><label className="siteflow-field"><span>Taille</span><input value={String(styles.fontSize ?? "")} onChange={(event) => onStyles({ fontSize: event.target.value })} placeholder="ex. 34px" /></label><label className="siteflow-field"><span>Padding</span><input value={String(styles.padding ?? "")} onChange={(event) => onStyles({ padding: event.target.value })} placeholder="ex. 28px" /></label></div></div> }
function PublishDialog({ site, pages, onClose, onPublish, loading }: { site: { slug: string; status: string }; pages: Array<{ name: string; settings: Record<string, unknown>; elementTree: ElementNode[] }>; onClose: () => void; onPublish: () => void; loading: boolean }) { const checks = [{ label: "Pages", detail: `${pages.length} page(s) prête(s)`, ok: pages.length > 0 }, { label: "Responsive", detail: "Les vues Desktop, Tablet et Mobile sont disponibles", ok: true }, { label: "SEO", detail: "Le titre est défini sur la page d’accueil", ok: Boolean(pages[0]?.settings.title) }, { label: "Images", detail: "Les visuels de votre template sont intégrés", ok: true }, { label: "Liens", detail: "Les liens de navigation sont vérifiés", ok: true }]; return <div className="siteflow-modal-backdrop"><section className="siteflow-dialog max-w-[560px]"><header className="flex justify-between border-b border-[#ECECF2] px-7 py-6"><div><p className="text-[10px] font-extrabold uppercase tracking-[.16em] text-[#6D70D8]">Prêt à publier</p><h2 className="mt-1 font-display text-[32px]">Votre checklist finale.</h2></div><button onClick={onClose} className="siteflow-icon-btn"><X className="h-4 w-4" /></button></header><div className="space-y-3 p-7">{checks.map((check) => <div key={check.label} className="flex items-center gap-3 rounded-xl border border-[#E6E6EE] bg-[#FAFAFC] p-4"><span className={`grid h-7 w-7 place-items-center rounded-full ${check.ok ? "bg-[#E8F6ED] text-[#287348]" : "bg-[#FFF1E5] text-[#AE6C28]"}`}>{check.ok ? <Check className="h-4 w-4" /> : "!"}</span><span><strong className="block text-xs">{check.label}</strong><small className="mt-0.5 block text-[11px] text-[#74778A]">{check.detail}</small></span></div>)}</div><footer className="flex justify-end gap-3 border-t border-[#ECECF2] px-7 py-5"><button onClick={onClose} className="siteflow-secondary-btn">Pas maintenant</button><button onClick={onPublish} disabled={loading} className="siteflow-primary-btn disabled:opacity-50"><Rocket className="h-4 w-4" />{loading ? "Publication…" : "Publier le site"}</button></footer></section></div> }
function PublishResult({ slug, onClose }: { slug: string; onClose: () => void }) { const url = `${window.location.origin}/s/${slug}`; return <div className="siteflow-modal-backdrop"><section className="siteflow-dialog max-w-[510px] p-9 text-center"><span className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-[#E8F7ED] text-[#2D7A4A]"><Check className="h-7 w-7" /></span><h2 className="mt-5 font-display text-[34px]">Votre site est en ligne.</h2><p className="mt-2 text-sm leading-6 text-[#717487]">Le même arbre de pages est maintenant disponible en version publique.</p><div className="mt-6 flex items-center gap-2 rounded-xl border border-[#E2E3ED] bg-[#FAFAFC] p-3 text-left"><Globe2 className="h-4 w-4 text-[#2925D8]" /><span className="min-w-0 flex-1 truncate text-xs font-semibold">{url}</span><button onClick={() => navigator.clipboard.writeText(url).then(() => toast.success("URL copiée."))} className="siteflow-icon-btn !h-8 !w-8"><Copy className="h-3.5 w-3.5" /></button></div><div className="mt-6 grid grid-cols-2 gap-3"><button onClick={onClose} className="siteflow-secondary-btn justify-center">Fermer</button><button onClick={() => window.open(url, "_blank")} className="siteflow-primary-btn justify-center">Visiter le site<ArrowUp className="h-4 w-4 rotate-45" /></button></div></section></div> }
function PanelShell({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) { return <div className="h-full overflow-y-auto p-5"><h2 className="font-display text-[28px] tracking-[-.035em]">{title}</h2><p className="mt-1 mb-6 text-xs leading-5 text-[#777A8D]">{subtitle}</p>{children}</div> }
function EmptyPanel({ icon: Icon, text }: { icon: typeof Database; text: string }) { return <div className="rounded-xl border border-dashed border-[#DCDC E8] bg-[#FAFAFC] p-4 text-center"><Icon className="mx-auto h-5 w-5 text-[#777BD7]" /><p className="mt-2 text-[11px] leading-5 text-[#7A7D8F]">{text}</p></div> }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-[#E5E5EE] bg-white p-3"><p className="text-[10px] font-bold uppercase tracking-[.08em] text-[#888B9C]">{label}</p><strong className="mt-1 block text-lg">{value}</strong></div> }
function SettingsRow({ icon: Icon, label, value }: { icon: typeof Globe2; label: string; value: string }) { return <div className="flex items-center gap-3 rounded-xl border border-[#E6E6EE] bg-white p-3"><Icon className="h-4 w-4 text-[#6569D4]" /><span className="min-w-0 flex-1"><strong className="block text-xs">{label}</strong><small className="block truncate pt-0.5 text-[11px] text-[#85889A]">{value}</small></span><ChevronRight className="h-4 w-4 text-[#A2A4B2]" /></div> }
